const data = {
  products: [
    {
      _id: '1',
      name: 'Boy Kaki Pullover',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 150,
      countInStock: 10,
      brand: 'Nike',
      rating: 4,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id: '2',
      name: 'Boy Sweatshirt, Pants',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 300,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.9,
      numReviews: 23,
      description: 'High quality product',
    },
    {
      _id: '3',
      name: 'Pink Neck Sweater',
      category: 'Sweaters',
      image: '/images/p3.jpg',
      price: 200,
      countInStock: 0,
      brand: 'La Rose',
      rating: 4.8,
      numReviews: 17,
      description: 'High quality product',
    },
    {
      _id: '4',
      name: 'Jean Jumpsuit',
      category: 'jumpsuit',
      image: '/images/p4.jpg',
      price: 250,
      countInStock: 23,
      brand: 'ZARA',
      rating: 3.7,
      numReviews: 14,
      description: 'High quality product',
    },
    {
      _id: '5',
      name: 'T-shirt and Shorts',
      category: 'Shirts',
      image: '/images/p5.jpg',
      price: 250,
      countInStock: 32,
      brand: 'Puma',
      rating: 4.8,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id: '6',
      name: 'White Girl Dress',
      category: 'Dress',
      image: '/images/p6.jpg',
      price: 350,
      countInStock: 7,
      brand: 'La Rose',
      rating: 4.5,
      numReviews: 15,
      description: 'High quality product',
    },
    {
      _id: '7',
      name: 'Astronaut Uniform',
      category: 'Uniforms',
      image: '/images/p7.jpg',
      price: 650,
      countInStock: 16,
      brand: 'Kids',
      rating: 5,
      numReviews: 35,
      description: 'High quality product',
    },
    {
      _id: '8',
      name: 'Military Uniform',
      category: 'Uniforms',
      image: '/images/p8.jpg',
      price: 550,
      countInStock: 42,
      brand: 'Kids',
      rating: 5,
      numReviews: 20,
      description: 'High quality product',
    },
    {
      _id: '9',
      name: 'Black Girl Dress',
      category: 'Dress',
      image: '/images/p9.jpg',
      price: 150,
      countInStock: 28,
      brand: 'Kids',
      rating: 3.5,
      numReviews: 7,
      description: 'High quality product',
    },
    {
      _id: '10',
      name: 'Girl pink sweater, skirt',
      category: 'Sweaters',
      image: '/images/p10.jpg',
      price: 350,
      countInStock: 5,
      brand: 'Kids',
      rating: 4.3,
      numReviews: 16,
      description: 'High quality product',
    },
  ],
};

export default data;
